"use strict";

(function productivityStrings(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.ClawdProductivityI18n = api;
})(globalThis, function createProductivityStrings() {
  const en = {
    sidebarProductivity: "Productivity", title: "Productivity tools", subtitle: "Quota reminders, quiet hours and your local project shortcuts.",
    quotaTitle: "Quota reminders", quotaDescription: "Get a reminder when a reported quota falls below your remaining-percentage thresholds.",
    quotaEnabled: "Enable quota reminders", quotaThresholds: "Remaining quota thresholds (%)", quotaThresholdHelp: "Enter 1–5 different whole percentages from 1 to 99, separated by commas. Example: 20, 10.",
    quotaRecovery: "Notify when quota recovers", quietTitle: "Quiet hours", quietEnabled: "Enable scheduled quiet hours",
    quietHelp: "Uses your computer’s local time. Overnight periods belong to the selected start day. Approvals return to the agent’s native interface during quiet hours. Manually showing the pet or putting it to sleep pauses the current scheduled period.",
    quietDays: "Start days", quietStart: "Starts at", quietEnd: "Ends at", quietHide: "Hide the pet during quiet hours",
    projectTitle: "Project bookmarks", projectDescription: "Save a folder and an opening mode. A project only opens when you click Open; no custom commands are run.",
    addProject: "Add project", projectName: "Project name", projectFolder: "Folder", chooseFolder: "Choose folder…", launchMode: "Open with",
    modeFolder: "File manager", modeTerminal: "Terminal", modeClaude: "Claude Code", modeCodex: "Codex CLI",
    save: "Save", saving: "Saving…", cancel: "Cancel", edit: "Edit", delete: "Remove bookmark", open: "Open", opening: "Opening…", saved: "Saved",
    saveFailed: "Could not save these settings.", launchFailed: "Could not open this project.", chooseFailed: "Could not choose a folder.", unavailable: "This feature is unavailable in this window.",
    invalidThresholds: "Use 1–5 different whole percentages from 1 to 99.", invalidQuiet: "Select at least one start day and two different valid times.",
    invalidProject: "Choose a folder, enter a name of 1–80 characters and select an opening mode.", limitProjects: "You can save up to 32 projects.", emptyProjects: "No projects saved yet.", missingProject: "This bookmark was removed in another window. Add it again to keep it.",
    dayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    quotaLowTitle: "Quota running low", quotaRecoveredTitle: "Quota recovered",
    quotaLowBody: "{provider} · {window}: {remaining}% remaining.", quotaRecoveredBody: "{provider} · {window}: quota recovered to {remaining}% remaining.",
    quotaWindowHours: "{n}-hour window", quotaWindowDays: "{n}-day window", quotaWindowMinutes: "{n}-minute window",
  };
  const translations = {
    zh: {
      sidebarProductivity: "效率工具", title: "效率工具", subtitle: "额度提醒、定时勿扰，以及本地项目快捷入口。",
      quotaTitle: "额度提醒", quotaDescription: "已获取的额度低于设定的剩余百分比时，提醒你留意用量。", quotaEnabled: "开启额度提醒", quotaThresholds: "剩余额度阈值（%）", quotaThresholdHelp: "填写 1–5 个不同的整数百分比（1–99），以逗号分隔，例如：20, 10。", quotaRecovery: "额度恢复时提醒",
      quietTitle: "定时勿扰", quietEnabled: "开启定时勿扰", quietHelp: "使用电脑本地时间。跨夜时段归属所选的开始日。勿扰期间，审批回到 Agent 原生界面。手动显示宠物或让其睡眠，可暂停当前定时时段。", quietDays: "开始日", quietStart: "开始时间", quietEnd: "结束时间", quietHide: "勿扰期间隐藏宠物",
      projectTitle: "项目书签", projectDescription: "保存文件夹和打开方式。只有点击「打开」才会启动项目；不会运行自定义命令。", addProject: "添加项目", projectName: "项目名称", projectFolder: "文件夹", chooseFolder: "选择文件夹…", launchMode: "打开方式", modeFolder: "文件管理器", modeTerminal: "终端", modeClaude: "Claude Code", modeCodex: "Codex CLI",
      save: "保存", saving: "保存中…", cancel: "取消", edit: "编辑", delete: "移除书签", open: "打开", opening: "打开中…", saved: "已保存", saveFailed: "未能保存设置。", launchFailed: "未能打开项目。", chooseFailed: "未能选择文件夹。", unavailable: "当前窗口暂不支持此功能。", invalidThresholds: "请填写 1–5 个不同的整数百分比（1–99）。", invalidQuiet: "请选择至少一个开始日，以及两个不同的有效时间。", invalidProject: "请选择文件夹，填写 1–80 字的名称，并选择打开方式。", limitProjects: "最多可保存 32 个项目。", emptyProjects: "尚未保存项目。", missingProject: "这个书签已在其他窗口移除；如需保留，请重新添加。", dayNames: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
      quotaLowTitle: "额度即将用尽", quotaRecoveredTitle: "额度已恢复", quotaLowBody: "{provider} · {window}：剩余 {remaining}%。", quotaRecoveredBody: "{provider} · {window}：额度已恢复，剩余 {remaining}%。", quotaWindowHours: "{n} 小时额度", quotaWindowDays: "{n} 天额度", quotaWindowMinutes: "{n} 分钟额度",
    },
    "zh-TW": {
      sidebarProductivity: "效率工具", title: "效率工具", subtitle: "額度提醒、定時勿擾，以及本機專案捷徑。", quotaTitle: "額度提醒", quotaDescription: "已取得的額度低於設定的剩餘百分比時，提醒你留意用量。", quotaEnabled: "開啟額度提醒", quotaThresholds: "剩餘額度門檻（%）", quotaThresholdHelp: "輸入 1–5 個不同的整數百分比（1–99），以逗號分隔，例如：20, 10。", quotaRecovery: "額度恢復時提醒",
      quietTitle: "定時勿擾", quietEnabled: "開啟定時勿擾", quietHelp: "使用電腦本機時間。跨夜時段歸屬所選的開始日。勿擾期間，審批回到 Agent 原生介面。手動顯示寵物或讓其睡眠，可暫停目前的定時時段。", quietDays: "開始日", quietStart: "開始時間", quietEnd: "結束時間", quietHide: "勿擾期間隱藏寵物",
      projectTitle: "專案書籤", projectDescription: "儲存資料夾與開啟方式。只有按下「開啟」才會啟動專案；不會執行自訂命令。", addProject: "新增專案", projectName: "專案名稱", projectFolder: "資料夾", chooseFolder: "選擇資料夾…", launchMode: "開啟方式", modeFolder: "檔案管理員", modeTerminal: "終端機", modeClaude: "Claude Code", modeCodex: "Codex CLI",
      save: "儲存", saving: "儲存中…", cancel: "取消", edit: "編輯", delete: "移除書籤", open: "開啟", opening: "開啟中…", saved: "已儲存", saveFailed: "無法儲存設定。", launchFailed: "無法開啟專案。", chooseFailed: "無法選擇資料夾。", unavailable: "目前視窗暫不支援此功能。", invalidThresholds: "請輸入 1–5 個不同的整數百分比（1–99）。", invalidQuiet: "請選擇至少一個開始日，以及兩個不同的有效時間。", invalidProject: "請選擇資料夾、輸入 1–80 字的名稱，並選擇開啟方式。", limitProjects: "最多可儲存 32 個專案。", emptyProjects: "尚未儲存專案。", missingProject: "這個書籤已在其他視窗移除；如需保留，請重新新增。", dayNames: ["週日", "週一", "週二", "週三", "週四", "週五", "週六"],
      quotaLowTitle: "額度即將用盡", quotaRecoveredTitle: "額度已恢復", quotaLowBody: "{provider} · {window}：剩餘 {remaining}%。", quotaRecoveredBody: "{provider} · {window}：額度已恢復，剩餘 {remaining}%。", quotaWindowHours: "{n} 小時額度", quotaWindowDays: "{n} 天額度", quotaWindowMinutes: "{n} 分鐘額度",
    },
    ja: {
      sidebarProductivity: "効率化ツール", title: "効率化ツール", subtitle: "利用枠の通知、定時の通知停止、ローカルプロジェクトへのショートカット。", quotaTitle: "利用枠の通知", quotaDescription: "取得した利用枠の残量が設定した割合を下回ると通知します。", quotaEnabled: "利用枠の通知を有効にする", quotaThresholds: "残量の通知しきい値（%）", quotaThresholdHelp: "1～99 の異なる整数を 1～5 個、カンマで区切って入力してください。例：20, 10。", quotaRecovery: "利用枠の回復時に通知する",
      quietTitle: "定時の通知停止", quietEnabled: "定時の通知停止を有効にする", quietHelp: "コンピューターの現地時刻を使用します。日をまたぐ時間帯は開始曜日に属します。この時間帯の承認は Agent の標準画面で行います。手動でペットを表示するか眠らせると、現在の時間帯を一時停止します。", quietDays: "開始曜日", quietStart: "開始時刻", quietEnd: "終了時刻", quietHide: "通知停止中はペットを隠す",
      projectTitle: "プロジェクトのブックマーク", projectDescription: "フォルダーと開き方を保存します。「開く」を押したときだけ起動し、独自のコマンドは実行しません。", addProject: "プロジェクトを追加", projectName: "プロジェクト名", projectFolder: "フォルダー", chooseFolder: "フォルダーを選択…", launchMode: "開き方", modeFolder: "ファイルマネージャー", modeTerminal: "ターミナル", modeClaude: "Claude Code", modeCodex: "Codex CLI",
      save: "保存", saving: "保存中…", cancel: "キャンセル", edit: "編集", delete: "ブックマークを削除", open: "開く", opening: "起動中…", saved: "保存しました", saveFailed: "設定を保存できませんでした。", launchFailed: "プロジェクトを開けませんでした。", chooseFailed: "フォルダーを選択できませんでした。", unavailable: "このウィンドウでは利用できません。", invalidThresholds: "1～99 の異なる整数の割合を 1～5 個入力してください。", invalidQuiet: "開始曜日を 1 つ以上と、異なる有効な時刻を 2 つ選んでください。", invalidProject: "フォルダー、1～80 文字の名前、開き方を指定してください。", limitProjects: "保存できるプロジェクトは 32 個までです。", emptyProjects: "保存済みのプロジェクトはありません。", missingProject: "このブックマークは別のウィンドウで削除されました。必要なら再度追加してください。", dayNames: ["日", "月", "火", "水", "木", "金", "土"],
      quotaLowTitle: "利用枠の残量が少なくなりました", quotaRecoveredTitle: "利用枠が回復しました", quotaLowBody: "{provider} · {window}：残り {remaining}%。", quotaRecoveredBody: "{provider} · {window}：利用枠が回復し、残り {remaining}% です。", quotaWindowHours: "{n} 時間枠", quotaWindowDays: "{n} 日間枠", quotaWindowMinutes: "{n} 分間枠",
    },
    ko: {
      sidebarProductivity: "생산성 도구", title: "생산성 도구", subtitle: "사용 한도 알림, 예약 방해 금지 및 로컬 프로젝트 바로가기.", quotaTitle: "사용 한도 알림", quotaDescription: "확인된 사용 한도의 남은 비율이 설정값 아래로 내려가면 알려줍니다.", quotaEnabled: "사용 한도 알림 사용", quotaThresholds: "남은 한도 기준 (%)", quotaThresholdHelp: "1–99 사이의 서로 다른 정수 1–5개를 쉼표로 구분하세요. 예: 20, 10.", quotaRecovery: "한도가 회복되면 알림",
      quietTitle: "예약 방해 금지", quietEnabled: "예약 방해 금지 사용", quietHelp: "컴퓨터의 현지 시간을 사용합니다. 자정을 넘는 시간대는 시작 요일에 속합니다. 이 시간에는 Agent의 기본 화면에서 승인합니다. 펫을 직접 표시하거나 재우면 현재 예약 시간대를 일시 중지합니다.", quietDays: "시작 요일", quietStart: "시작 시간", quietEnd: "종료 시간", quietHide: "방해 금지 시간에 펫 숨기기",
      projectTitle: "프로젝트 북마크", projectDescription: "폴더와 여는 방식을 저장합니다. 열기를 눌러야 시작되며 사용자 지정 명령은 실행하지 않습니다.", addProject: "프로젝트 추가", projectName: "프로젝트 이름", projectFolder: "폴더", chooseFolder: "폴더 선택…", launchMode: "여는 방식", modeFolder: "파일 관리자", modeTerminal: "터미널", modeClaude: "Claude Code", modeCodex: "Codex CLI",
      save: "저장", saving: "저장 중…", cancel: "취소", edit: "편집", delete: "북마크 제거", open: "열기", opening: "여는 중…", saved: "저장됨", saveFailed: "설정을 저장하지 못했습니다.", launchFailed: "프로젝트를 열지 못했습니다.", chooseFailed: "폴더를 선택하지 못했습니다.", unavailable: "이 창에서는 사용할 수 없습니다.", invalidThresholds: "1–99 사이의 서로 다른 정수 비율 1–5개를 입력하세요.", invalidQuiet: "시작 요일을 하나 이상 고르고 서로 다른 유효한 시간 두 개를 선택하세요.", invalidProject: "폴더, 1–80자 이름 및 여는 방식을 지정하세요.", limitProjects: "프로젝트는 최대 32개까지 저장할 수 있습니다.", emptyProjects: "저장된 프로젝트가 없습니다.", missingProject: "다른 창에서 이 북마크를 제거했습니다. 필요하면 다시 추가하세요.", dayNames: ["일", "월", "화", "수", "목", "금", "토"],
      quotaLowTitle: "남은 사용 한도가 적습니다", quotaRecoveredTitle: "사용 한도가 회복됨", quotaLowBody: "{provider} · {window}: {remaining}% 남음.", quotaRecoveredBody: "{provider} · {window}: 한도가 회복되어 {remaining}% 남았습니다.", quotaWindowHours: "{n}시간 한도", quotaWindowDays: "{n}일 한도", quotaWindowMinutes: "{n}분 한도",
    },
    "pt-BR": {
      sidebarProductivity: "Produtividade", title: "Ferramentas de produtividade", subtitle: "Alertas de cota, horários silenciosos e atalhos para seus projetos locais.", quotaTitle: "Alertas de cota", quotaDescription: "Receba um aviso quando uma cota informada ficar abaixo das porcentagens restantes configuradas.", quotaEnabled: "Ativar alertas de cota", quotaThresholds: "Limites de cota restante (%)", quotaThresholdHelp: "Digite de 1 a 5 porcentagens inteiras diferentes, de 1 a 99, separadas por vírgulas. Exemplo: 20, 10.", quotaRecovery: "Avisar quando a cota se recuperar",
      quietTitle: "Horários silenciosos", quietEnabled: "Ativar horários silenciosos", quietHelp: "Usa o horário local do computador. Períodos que atravessam a meia-noite pertencem ao dia de início. As aprovações voltam à interface nativa do Agent nesse período. Mostrar o pet ou colocá-lo para dormir manualmente pausa o período atual.", quietDays: "Dias de início", quietStart: "Início", quietEnd: "Fim", quietHide: "Ocultar o pet no horário silencioso",
      projectTitle: "Projetos favoritos", projectDescription: "Salve uma pasta e um modo de abertura. O projeto só inicia ao clicar em Abrir; comandos personalizados não são executados.", addProject: "Adicionar projeto", projectName: "Nome do projeto", projectFolder: "Pasta", chooseFolder: "Escolher pasta…", launchMode: "Abrir com", modeFolder: "Gerenciador de arquivos", modeTerminal: "Terminal", modeClaude: "Claude Code", modeCodex: "Codex CLI",
      save: "Salvar", saving: "Salvando…", cancel: "Cancelar", edit: "Editar", delete: "Remover favorito", open: "Abrir", opening: "Abrindo…", saved: "Salvo", saveFailed: "Não foi possível salvar as configurações.", launchFailed: "Não foi possível abrir o projeto.", chooseFailed: "Não foi possível escolher uma pasta.", unavailable: "Este recurso não está disponível nesta janela.", invalidThresholds: "Use de 1 a 5 porcentagens inteiras diferentes, de 1 a 99.", invalidQuiet: "Selecione pelo menos um dia de início e dois horários válidos diferentes.", invalidProject: "Escolha uma pasta, um nome de 1 a 80 caracteres e um modo de abertura.", limitProjects: "Você pode salvar até 32 projetos.", emptyProjects: "Nenhum projeto salvo ainda.", missingProject: "Este favorito foi removido em outra janela. Adicione-o novamente para mantê-lo.", dayNames: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
      quotaLowTitle: "Cota quase esgotada", quotaRecoveredTitle: "Cota recuperada", quotaLowBody: "{provider} · {window}: {remaining}% restante.", quotaRecoveredBody: "{provider} · {window}: cota recuperada, com {remaining}% restante.", quotaWindowHours: "Janela de {n} horas", quotaWindowDays: "Janela de {n} dias", quotaWindowMinutes: "Janela de {n} minutos",
    },
    es: {
      sidebarProductivity: "Productividad", title: "Herramientas de productividad", subtitle: "Avisos de cuota, horarios silenciosos y accesos a tus proyectos locales.", quotaTitle: "Avisos de cuota", quotaDescription: "Recibe un aviso cuando una cuota informada baje de los porcentajes restantes que hayas configurado.", quotaEnabled: "Activar avisos de cuota", quotaThresholds: "Umbrales de cuota restante (%)", quotaThresholdHelp: "Introduce entre 1 y 5 porcentajes enteros distintos del 1 al 99, separados por comas. Ejemplo: 20, 10.", quotaRecovery: "Avisar cuando se recupere la cuota",
      quietTitle: "Horarios silenciosos", quietEnabled: "Activar horarios silenciosos", quietHelp: "Usa la hora local del equipo. Los períodos que pasan de medianoche pertenecen al día de inicio. Durante este horario, las aprobaciones vuelven a la interfaz nativa del Agent. Mostrar la mascota o ponerla a dormir manualmente pausa el período actual.", quietDays: "Días de inicio", quietStart: "Hora de inicio", quietEnd: "Hora de fin", quietHide: "Ocultar la mascota durante el horario silencioso",
      projectTitle: "Proyectos favoritos", projectDescription: "Guarda una carpeta y un modo de apertura. El proyecto solo se inicia al pulsar Abrir; no se ejecutan comandos personalizados.", addProject: "Añadir proyecto", projectName: "Nombre del proyecto", projectFolder: "Carpeta", chooseFolder: "Elegir carpeta…", launchMode: "Abrir con", modeFolder: "Gestor de archivos", modeTerminal: "Terminal", modeClaude: "Claude Code", modeCodex: "Codex CLI",
      save: "Guardar", saving: "Guardando…", cancel: "Cancelar", edit: "Editar", delete: "Quitar favorito", open: "Abrir", opening: "Abriendo…", saved: "Guardado", saveFailed: "No se pudo guardar la configuración.", launchFailed: "No se pudo abrir el proyecto.", chooseFailed: "No se pudo elegir una carpeta.", unavailable: "Esta función no está disponible en esta ventana.", invalidThresholds: "Usa entre 1 y 5 porcentajes enteros distintos del 1 al 99.", invalidQuiet: "Selecciona al menos un día de inicio y dos horas válidas distintas.", invalidProject: "Elige una carpeta, un nombre de 1 a 80 caracteres y un modo de apertura.", limitProjects: "Puedes guardar hasta 32 proyectos.", emptyProjects: "Todavía no hay proyectos guardados.", missingProject: "Este favorito se eliminó en otra ventana. Añádelo de nuevo para conservarlo.", dayNames: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
      quotaLowTitle: "Queda poca cuota", quotaRecoveredTitle: "Cuota recuperada", quotaLowBody: "{provider} · {window}: queda un {remaining}%.", quotaRecoveredBody: "{provider} · {window}: la cuota se recuperó y queda un {remaining}%.", quotaWindowHours: "Ventana de {n} horas", quotaWindowDays: "Ventana de {n} días", quotaWindowMinutes: "Ventana de {n} minutos",
    },
  };
  const notificationStrings = {
    en: { notificationTest: "Test notification", notificationTestTitle: "Clawd notification test", notificationTestBody: "Quota reminders can use this notification channel. No quota data or alert history was changed.", notificationTestSent: "The system accepted the test notification.", notificationTestFailed: "Notification was not shown. Check Do Not Disturb and your system notification settings.", quotaCollectionHelp: "Reminders use existing quota reports. Enable the provider’s usage collection first if needed. Cached data alone does not trigger reminders." },
    zh: { notificationTest: "测试通知", notificationTestTitle: "Clawd 通知测试", notificationTestBody: "额度提醒可使用此通知通道。本次测试不修改额度数据或提醒记录。", notificationTestSent: "系统已接受测试通知。", notificationTestFailed: "通知未能显示，请检查勿扰模式和系统通知设置。", quotaCollectionHelp: "提醒使用现有额度上报；如需开启该提供方的用量收集，请先在对应设置中启用。仅有缓存数据不会触发提醒。" },
    "zh-TW": { notificationTest: "測試通知", notificationTestTitle: "Clawd 通知測試", notificationTestBody: "額度提醒可使用此通知管道。本次測試不修改額度資料或提醒記錄。", notificationTestSent: "系統已接受測試通知。", notificationTestFailed: "通知無法顯示，請檢查勿擾模式與系統通知設定。", quotaCollectionHelp: "提醒使用現有額度回報；如需開啟供應商的用量收集，請先在對應設定中啟用。僅有快取資料不會觸發提醒。" },
    ja: { notificationTest: "通知をテスト", notificationTestTitle: "Clawd 通知テスト", notificationTestBody: "使用枠の通知はこの通知経路を使用できます。使用枠データや通知履歴は変更していません。", notificationTestSent: "システムがテスト通知を受け付けました。", notificationTestFailed: "通知を表示できませんでした。おやすみモードとシステムの通知設定を確認してください。", quotaCollectionHelp: "既存の使用枠レポートを使用します。必要に応じて提供元の使用量収集を有効にしてください。キャッシュのみでは通知しません。" },
    ko: { notificationTest: "알림 테스트", notificationTestTitle: "Clawd 알림 테스트", notificationTestBody: "사용 한도 알림은 이 알림 채널을 사용할 수 있습니다. 사용 한도 데이터와 알림 기록은 변경하지 않았습니다.", notificationTestSent: "시스템이 테스트 알림을 수락했습니다.", notificationTestFailed: "알림을 표시하지 못했습니다. 방해 금지 모드와 시스템 알림 설정을 확인하세요.", quotaCollectionHelp: "기존 사용 한도 보고를 사용합니다. 필요한 경우 공급자의 사용량 수집을 먼저 활성화하세요. 캐시 데이터만으로는 알림을 보내지 않습니다." },
    "pt-BR": { notificationTest: "Testar notificação", notificationTestTitle: "Teste de notificação do Clawd", notificationTestBody: "Os alertas de cota podem usar este canal. Nenhum dado de cota ou histórico de alertas foi alterado.", notificationTestSent: "O sistema aceitou a notificação de teste.", notificationTestFailed: "A notificação não apareceu. Confira o modo Não Perturbe e as configurações de notificações do sistema.", quotaCollectionHelp: "Os alertas usam os relatórios de cota existentes. Ative a coleta de uso do provedor se necessário. Dados em cache não disparam alertas sozinhos." },
    es: { notificationTest: "Probar notificación", notificationTestTitle: "Prueba de notificación de Clawd", notificationTestBody: "Los avisos de cuota pueden usar este canal. No se modificaron los datos de cuota ni el historial de avisos.", notificationTestSent: "El sistema aceptó la notificación de prueba.", notificationTestFailed: "No se mostró la notificación. Comprueba No molestar y los ajustes de notificaciones del sistema.", quotaCollectionHelp: "Los avisos usan los informes de cuota existentes. Activa la recopilación de uso del proveedor si es necesario. Los datos en caché por sí solos no generan avisos." },
  };
  const STRINGS = Object.freeze(Object.fromEntries(["en", ...Object.keys(translations)].map((lang) => [
    lang, Object.freeze({ ...en, ...(translations[lang] || {}), ...notificationStrings[lang] }),
  ])));
  return { STRINGS, getProductivityStrings(lang) { return STRINGS[lang] || STRINGS.en; } };
});
